### PR TITLE
Expose websocket cookie

### PR DESCRIPTION
**Pull request by gerad**
https://github.com/emqx/emqx-auth-http/issues/224

### CODE REVIEW

**Comment by HJianBo** [comment]
Thanks for your contribution @gerad. This is a very useful option!

First, one problem is that `ws_cookie` is a composite structure, it is not a value type. So it should be works only on the `application/json` mode. It couldn't encode to a `x-www-form-urlencoded` required form.

see: https://github.com/emqx/emqx/blob/897f862d29b45bd1585bc2ba3a122e8f5368ffc4/src/emqx_types.erl#L139

**Comment by gerad** [comment]
Any advice on how to proceed?

**Comment by HJianBo** [comment]
I think there are several possible ways:

1. Encode the ws_cookie as a json string and treat it as a whole and encode it. For example:  `cookie=%k` can be rendered to `cookie={"aKey":  true}`

2. Support `.` syntax to get a certain value in the cookie. For example: `cookie=%k.aKey` can be rendered to `cookie=aKey`

3. Disable the use of %k placeholder in the `x-www-form-urlencoded` type

Even the first two can be supported at the same time, they are not mutually exclusive. What do you think?

It's worth noting that with the first approach, the entire JSON may need to be URLENCODE once before filling in the HTTP Body? I'm not quite sure here, and will need to dig through the relevant specs.

**Comment by HJianBo** [comment]
If you have the interest and free time, you can try it out. Otherwise, we can make it happen. It doesn't matter.

Anyway, I look forward to your feedback. And discuss whether they make sense.

**Comment by gerad** [comment]
Thanks for getting back to me. I have the necessary HTTP skills but not the necessary erlang skills. :-)

For sending the cookie over form encoding, I think it'd make the most sense to send the cookie as a string in the same format as it's encoded in the http header. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Attributes

This might also be fine for the JSON response.

It would need to be url encoded for the GET request, but it's really bad form to put a cookie string in a url (similar to what the docs mention for passwords)… so I don't know if we want to encourage it.

**Comment by gerad** [comment]
Would love it if you could take this over. As much as this seems the perfect opportunity to learn erlang, I can't justify the time investment on it right now.

**Comment by zmstone** [comment]
> Thanks for your contribution @gerad. This is a very useful option!
> 
> First, one problem is that `ws_cookie` is a composite structure, it is not a value type. So it should be works only on the `application/json` mode. It couldn't encode to a `x-www-form-urlencoded` required form.
> 
> see: https://github.com/emqx/emqx/blob/897f862d29b45bd1585bc2ba3a122e8f5368ffc4/src/emqx_types.erl#L139

the spec `maybe(list())` for `ws_cookie` is rather vague, by any chance can we make it more clear ?

**Comment by zmstone** [comment]
to start with, we can get the cookie delivered in json body only.

**Comment by HJianBo** [comment]
Got it. @zmstone 
So here's the deal, in 4.3.0 I started by coding the ws_cookie in JSON.

Okay @gerad Then I commit the changes mentioned here to PR in dev/v4.3.0 under the emqx/emqx project. Thank you very much for your contribution!

**Comment by zmstone** [comment]
Hi @gerad 
I'm not sure if you are aware of this, (if not, there is clearly some miscommunication, sorry about that).
https://github.com/emqx/emqx/pull/3982 was merged, but then 
https://github.com/emqx/emqx/pull/4009 reverted the changes

We have received some concerns about security issues this change may imply.
@HJianBo @wivwiv could you guys add more details ?

**Comment by wivwiv** [comment]
Using cookie authentication goes beyond the mqtt username / ClientID + passsword authentication system. In fact, you should handle it on the client.

You should find a way to carry cookies into mqtt connection information, or use additional ways to issue authentication information to clients. I believe this is more effective and simple than modifying EMQ X.

### Client
```
import mqtt from 'mqtt'
import axios from 'axios'

async function conn() {
  // Issue a token for MQTT connect auth
  const resp = await axios.get('/get-mqtt-token')
  const token = resp.data.token

  // or use local cookie, It doesn't have to work
  // const token = document.cookie

 const client = mqtt.connect('ws://broker.emqx.io:8083/mqtt', {
   username: 'your username',
   password: token
 })

}
```


### emqx-auth-http
```
auth.http.auth_req.params = clientid=%c,username=%u,password=%P
# %P is your cookie or token
```

### Auth server such as Koa

```
app.post('/mqtt-auth', async (ctx, next) => {
   if (ctx.body.password === 'some value') {
     ctx.body = ''
     return await next()
   }
})
```

**Pull request closed without merging**
