### PR TITLE
add http header (Cookies etc...) support

### PR DESCRIPTION
**Pull request by zhangjiayin**
add http header (Cookies etc...) support 
by pass %h format 

eg
auth.http.auth_req.params = username=%u,password=%P,clientid=%c,ipaddr=%a,ws_initial_headers=%h

### CODE REVIEW

**Comment by emqplus** [comment]
@zhangjiayin Thanks for you contributions. The `ws_initial_headers` is only available for Websocket connections. Could you explain the use case in detail?

**Comment by zhangjiayin** [comment]
we want to use emq for notifaction on both mobile and h5 , Original websocket  in emq can not pass cookie and other header  to auth req ，and we cannot  pass some password in plain text , so I add this feature to emq-auth-http for  authentication

**Comment by zhangjiayin** [comment]
will this pull request be merged  for  2.1.1  ?

**Comment by emqplus** [comment]
@zhangjiayin This PR will be merged in 2.2-beta.1 release.

**Comment by zhangjiayin** [comment]
thks， we'll use it  self patched .

**Comment by zhangjiayin** [comment]
Does this pr is merged to 2.2-beta.1 ?

**Comment by Gilbert-Wong** [comment]
Sorry for so late response, the cookies in websocket headers has been set into credentials in emqx3.1-rc.2. I will close this pull request. Welcome for your new pull request if you want do `auth and acl` check based on websocket cookie.

**Pull request closed without merging**
